---
title: "L'étiquette politique des élus locaux influence-t-elle l'artificialisation des sols à des fins industrielles et logistiques ?"
author: "Caroline Lebrun-Sabalot, Pierre Ripoll, Matéo Garbe"
format:
  html:
    toc: true
    theme: cosmo
    self-contained: true
execute: 
    echo: false
---


```{r}
#| echo: false
#| output: false

packages <- c("dplyr", "ggplot2", "reticulate", "rdrobust","dotenv","plotly","shiny", "dotenv")

# Installer seulement ceux qui ne sont pas déjà installés
install_if_missing <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
}

lapply(packages, install_if_missing)
```

```{r}
#| echo: false
#| output: false
library(dotenv)
library(ggplot2)
library(dplyr)
library(reticulate)
library(dotenv)
library(plotly)
library(shiny)
```




```{r}
#| echo: false
#| output: false
#| context: setup
setwd("/home/onyxia/work/projet3A")
# Charger les fonctions
source("functions/main_functions.R")

#chargement des var d'env pour Caro
if (file.exists(".env")) {
  dotenv::load_dot_env(".env")
} 

# Télécharger le CSV du RDD
remote_path <- "RDD/df_RDD_main_BC_full.csv"
gdf_RDD<-get_s3_csv("mgarbe",remote_path)

# Télécharger le CSV pour les stats desc du vote
remote_path_elec="Elections/donnees_duel_maires_wide.csv"
gdf_vote<-get_s3_csv("mgarbe",remote_path_elec, delim_csv = ",")

```


## Répartition des votes

::: {.panel-tabset}

```{r}
#| echo: false
#| results: asis
#| warning: false


# Quelques statistiques sur les variables du vote pour 2014
cat(paste0("## 2014 \n\n"))
hist(gdf_vote$rang1_voix_pct[gdf_vote$annee == 2014], 
xlab = "Pourcentage de voix obtenu par le gagnant", 
ylab = "")
cat("\n\n")

cat(paste0("## 2020 \n\n"))
# Quelques statistiques sur les variables du vote pour 2020
hist(gdf_vote$rang1_voix_pct[gdf_vote$annee == 2020], 
xlab = "Pourcentage de voix obtenu par le gagnant", 
ylab = "")
cat("\n\n")

``` 

:::


# Balanced Checks 

```{r}
#| echo: false
#| output: false
#| context: data

#récupérer l'objet Python
seuil <- 8
gdf_RDD_seuil <- gdf_RDD %>% filter(abs(delta_score_1) < seuil)
```

::: {.panel-tabset}

```{r}
#| echo: false
#| results: asis
#| warning: false

# Variables BC
bc_vars <- grep("^BC_", names(gdf_RDD_seuil), value = TRUE)
tab_names <- c("Population", "Densité de population", "Chômage", "Emploi")
stopifnot(length(bc_vars) == length(tab_names))

for (i in seq_along(bc_vars)) {
  # Titre de l'onglet
  cat(paste0("## ", tab_names[i], "\n\n"))
  p <- plot_rdd(gdf_RDD_seuil, outcome_var = bc_vars[i])
  print(p)
  cat("\n\n")
}

```

:::

# Régressions

```{r, echo=FALSE}
# Fonction pour générer graphique + table
rdd_report <- function(data, outcome_var, kernel, effet_fixe = NULL,elections= c("2014_muni", "2020_muni")) {
  # Graphique
  p <- plot_rdd_kernel(data, outcome_var = outcome_var,kernel)
  
    # Table RDD
  if (!is.null(effet_fixe)) {
    tab <- compute_rdd(
      df = data,
      outcome_var = outcome_var,
      kernel_choisi = kernel,
      cov_choisies = effet_fixe,
      elections = elections
    )
  } else {
    tab <- compute_rdd(
      df = data,
      outcome_var = outcome_var,
      kernel_choisi = kernel,
      cov_choisies = NULL,
      elections = elections
    )
  }
  
  # Retourne un tibble/table + graphique dans une liste
  list(
    plot = p,
    table = tab
  )
}

```

::: {.panel-tabset}

## Fig. kernel uni
```{r}
res_uni <- rdd_report(gdf_RDD_seuil, "surface_creee", kernel = "uni") #add Nuance_interco
print(res_uni$plot)
```


## Tab. kernel uni

```{r}
print(res_uni$tab)
```


## Fig. kernel tri

```{r}
res_tri <- rdd_report(gdf_RDD_seuil, "surface_creee", kernel = "tri")
print(res_tri$plot)
```


## Tab. kernel tri

```{r}
print(res_tri$tab)
```


:::

<!-- ::: {.panel-tabset}-->

<!--  ## Avec kernel uniforme -->
```{r,eval=FALSE}
#| echo: false
rdd_unif = compute_rdd(gdf_RDD_seuil,
                        outcome_var = "surface_creee", 
                        kernel_choisi = "uni",
                        election = "2020_muni")
rdd_unif$Estimate
rdd_unif$pv
```


<!--  ## Avec kernel triangulaire -->
```{r,eval=FALSE}
#| echo: false
rdd_tri = compute_rdd(gdf_RDD_seuil,
                        outcome_var = "surface_creee", 
                        kernel_choisi = "tri",
                        election_choisie = "2014_muni")
print(rdd_tri)
rdd_tri$Estimate
rdd_tri$pv
```


<!-- ## Avec kernel uniforme -->
```{r,eval=FALSE}
#| echo: false
rdd_unif = compute_rdd(gdf_RDD_seuil,
                        outcome_var = "surface_creee", 
                        kernel_choisi = "uni",
                        election_choisie = "2014_muni")
rdd_unif$Estimate
rdd_unif$pv
```

<!--:::-->
